### ISSUE TITLE
Questions about data preprocessing

### ISSUE THREAD

**Issue by zoomkinseok** [63days/PartGlot#1]
Hi, 
thanks for your great work!
I can get the preprocessed data from your repo, but I'm curious about the preprocessing process.
Can you tell me specifically how you got the super-segment in BSP-Net?
Did you sample a constant number of points for each primitive(convex)?

Thanks
Best,

**Comment by zoomkinseok** [comment]
Hi, 
thanks for your great work!
I can get the preprocessed data from your repo, but I'm curious about the preprocessing process.
Can you tell me specifically how you got the super-segment in BSP-Net?
Did you sample a constant number of points for each primitive(convex)?

Thanks
Best,

**Comment by 63days** [comment]
I appreciate your interest in our work. I'll explain the super-segment generation process in more detail. After assigning 2048 points to each closest primitive, the number of points in each primitive differs. So, we duplicated or sampled points in each primitive so that all primitives had 512 points.

**Comment by zoomkinseok** [comment]
Thank you for answer. I understand!

Best regards
Minseok Joo
2022년 7월 18일 (월) 오후 1:36, Juil Koo ***@***.***>님이 작성:
